theme: jekyll-theme-minimal

title: HarmonicaScaler
description: For anyone interested in music theory and want to learn the correlation between scales this app would be exciting; particularly if you play the harmonica which up on the scales are applied
logo: assets/icons/icon-192x192.png
